### PR TITLE
SPDX and Foundation setup

### PR DESCRIPTION
**Pull request by lsf37**

### CODE REVIEW

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit c0d4c125ebbd69ecfcf220ce552de4a25238c3cd

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - sel4test-manifest - EXT-seL4-spdx-8 | FAILED |
| Code Quality - Style - sel4test-manifest - EXT-seL4-spdx-8 | SUCCESSFUL |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Check licenses - sel4test-manifest - EXT-seL4-spdx-8 | Check licenses | 1 of 1 job failed |

**Job: lic**
Build logs

    03-Dec-2020 20:44:09	Build Code Quality - Check licenses - sel4test-manifest - EXT-seL4-spdx-8 - lic #1 (CQ-SEL4TESTMANIFESTCL7-SEL4TESTMANIFESTLICCQ-1) started building on agent A local agent 2, bamboo version: 7.1.4
    03-Dec-2020 20:44:09	I run on the Bamboo server!
    03-Dec-2020 20:44:09	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTMANIFESTCL7-SEL4TESTMANIFESTLICCQ
    03-Dec-2020 20:44:09	Executing build Code Quality - Check licenses - sel4test-manifest - EXT-seL4-spdx-8 - lic #1 (CQ-SEL4TESTMANIFESTCL7-SEL4TESTMANIFESTLICCQ-1)
    03-Dec-2020 20:44:09	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTMANIFESTCL7-SEL4TESTMANIFESTLICCQ/. (location: .)
    03-Dec-2020 20:44:09	Artifact 'code' prepared in 8.163 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTMANIFESTCL7-SEL4TESTMANIFESTLICCQ/./code.tar.gz
    03-Dec-2020 20:44:09	Running pre-build action: VCS Version Collector
    03-Dec-2020 20:44:09	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    03-Dec-2020 20:44:09	+ tar xf code.tar.gz --recursive-unlink
    03-Dec-2020 20:44:09	Finished task 'Untar code' with result: Success
    03-Dec-2020 20:44:09	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    03-Dec-2020 20:44:09	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTMANIFESTCL7-SEL4TESTMANIFESTLICCQ
    03-Dec-2020 20:44:09	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    03-Dec-2020 20:44:09	Starting task 'Check license' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    03-Dec-2020 20:44:09	+ python license-tool/check_license.py sel4test-manifest
    03-Dec-2020 20:44:09	ERROR:root:sel4test-manifest/README.md: sel4test-manifest/README.md: no owner found
    03-Dec-2020 20:44:09	ERROR:root:sel4test-manifest/common.xml: sel4test-manifest/common.xml: no owner found
    03-Dec-2020 20:44:09	ERROR:root:sel4test-manifest/default.xml: sel4test-manifest/default.xml: no owner found
    03-Dec-2020 20:44:09	ERROR:root:sel4test-manifest/master.xml: sel4test-manifest/master.xml: no owner found
    03-Dec-2020 20:44:09	ERROR:root:sel4test-manifest/.github/CODE_OF_CONDUCT.md: sel4test-manifest/.github/CODE_OF_CONDUCT.md: no owner found
    03-Dec-2020 20:44:09	ERROR:root:sel4test-manifest/.github/CONTRIBUTING.md: sel4test-manifest/.github/CONTRIBUTING.md: no owner found
    03-Dec-2020 20:44:09	ERROR:root:sel4test-manifest/.github/LICENSE.md: sel4test-manifest/.github/LICENSE.md: no owner found
    03-Dec-2020 20:44:09	ERROR:root:sel4test-manifest/.github/workflows/pr.yml: sel4test-manifest/.github/workflows/pr.yml: no owner found
    03-Dec-2020 20:44:09	ERROR:root:sel4test-manifest/.github/workflows/push.yml: sel4test-manifest/.github/workflows/push.yml: no owner found
    03-Dec-2020 20:44:09	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4TESTMANIFESTCL7-SEL4TESTMANIFESTLICCQ-1-ScriptBuildTask-4060974216597418424.sh] was 1 while expected 0
    03-Dec-2020 20:44:09	Finished task 'Check license' with result: Failed
    03-Dec-2020 20:44:09	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    03-Dec-2020 20:44:09	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTMANIFESTCL7-SEL4TESTMANIFESTLICCQ
    03-Dec-2020 20:44:09	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    03-Dec-2020 20:44:09	Running post build plugin 'NCover Results Collector'
    03-Dec-2020 20:44:09	Running post build plugin 'Artifact Copier'
    03-Dec-2020 20:44:09	Running post build plugin 'npm Cache Cleanup'
    03-Dec-2020 20:44:09	Running post build plugin 'Clover Results Collector'
    03-Dec-2020 20:44:09	Running post build plugin 'Docker Container Cleanup'
    03-Dec-2020 20:44:09	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TESTMANIFESTCL7-SEL4TESTMANIFESTLICCQ'
    03-Dec-2020 20:44:09	Finalising the build...
    03-Dec-2020 20:44:09	Stopping timer.
    03-Dec-2020 20:44:09	Build CQ-SEL4TESTMANIFESTCL7-SEL4TESTMANIFESTLICCQ-1 completed.
    03-Dec-2020 20:44:09	Running on server: post build plugin 'NCover Results Collector'
    03-Dec-2020 20:44:09	Running on server: post build plugin 'Build Hanging Detection Configuration'
    03-Dec-2020 20:44:09	Running on server: post build plugin 'Clover Delta Calculator'
    03-Dec-2020 20:44:09	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    03-Dec-2020 20:44:09	All post build plugins have finished
    03-Dec-2020 20:44:09	Generating build results summary...
    03-Dec-2020 20:44:09	Saving build results to disk...
    03-Dec-2020 20:44:09	Store variable context...
    03-Dec-2020 20:44:09	Indexing build results...
    03-Dec-2020 20:44:09	Finished building CQ-SEL4TESTMANIFESTCL7-SEL4TESTMANIFESTLICCQ-1.


This is the most I can report on right now, sorry!

**Review by kent-mcleod — APPROVED** [review]

**Review by xurtis — APPROVED** [review]

**Comment by lsf37** [comment]
Merged in 546384c6

**Pull request closed without merging**
